[package]
name = "server"
version = "0.1.0"
authors = ["busyluo <2488091@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
protobuf-codegen-pure = "2.8.1"