[package]
name = "test_for_each"
version = "0.1.0"
authors = ["busyluo <2488091@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version="0.2.9", features=["full"]}
futures="0.3"